# Generated by Django 6.0.3 on 2026-05-18 15:41
# Migration: Grading Model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

#
class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('Quiz', 'Quiz'), ('Exam', 'Exam'), ('Project', 'Project'), ('Activity', 'Activity')], max_length=20)),
                ('score', models.FloatField()),
                ('total_items', models.FloatField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.record')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.schedule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
