# Generated by Django 6.0.3 on 2026-05-18 16:24
# Migration: Roster Constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

#
class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.schedule')),
                ('students', models.ManyToManyField(to='attendance_app.record')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'schedule')},
            },
        ),
    ]
